import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import Database from "better-sqlite3";
import { databasePath, openDatabase } from "./db/client.js";
import { OrchestrationStore } from "./orchestration-store.js";

test("version 18 session DB upgrades atomically, survives an injected migration crash, and restarts idempotently", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "devspace-migration-19-"));
  t.after(async () => rm(dir, { recursive: true, force: true }));
  const first = new OrchestrationStore(dir);
  const original = first.createSession({ id: "legacy", projectKey: "p", workspaceRoot: dir, state: "running" });
  first.close();
  // Reconstruct the exact pre-19 session columns in an isolated fixture DB.
  const legacy = new Database(databasePath(dir));
  legacy.exec(`drop index coordinator_tasks_attempt;
    alter table coordinator_tasks drop column attempt_id;
    alter table coordinator_tasks drop column lease_generation;
    alter table coordinator_tasks drop column owner_worker_incarnation_id;
    drop index orchestration_sessions_logical;
    alter table orchestration_sessions drop column logical_session_id;
    alter table orchestration_sessions drop column worker_incarnation_id;
    drop table orchestration_execution_evidence;
    drop table orchestration_test_runs;
    alter table orchestration_sessions drop column last_test_attempt_at;
    alter table orchestration_sessions drop column last_successful_validation_at;
    alter table orchestration_sessions drop column last_validation_failure_at;
    alter table orchestration_sessions drop column last_validated_commit;
    alter table orchestration_sessions drop column last_validated_tree;
    alter table orchestration_sessions drop column last_validated_file_generation;
    drop table workspace_access_config_serialization;
    drop table workspace_access_managed_roots;
    drop table workspace_access_operations;
    drop index workspace_access_grant_operation;
    alter table workspace_access_grants drop column activation_state;
    alter table workspace_access_grants drop column operation_id;
    alter table workspace_access_grants drop column use_generation;
    alter table workspace_access_requests drop column revision;
    alter table workspace_access_requests drop column decision_operation_id;
    drop index orchestration_events_kind_idx;
    alter table orchestration_sessions drop column revision;
    alter table orchestration_sessions drop column incarnation;
    alter table orchestration_sessions drop column binding_generation;
    alter table orchestration_sessions drop column file_generation;
    delete from devspace_schema_migrations where version >= 19;
    create trigger injected_migration_crash before insert on devspace_schema_migrations
      when new.version = 19 begin select raise(abort, 'injected migration crash'); end;`);
  legacy.close();
  assert.throws(() => openDatabase(dir), /injected migration crash/);
  const inspect = new Database(databasePath(dir));
  const columns = inspect.prepare("pragma table_info(orchestration_sessions)").all() as Array<{ name: string }>;
  assert.equal(columns.some(column => column.name === "revision"), false, "schema changes rolled back with the failed ledger insert");
  inspect.exec("drop trigger injected_migration_crash");
  inspect.close();
  const upgraded = new OrchestrationStore(dir);
  assert.equal(upgraded.getSession("legacy")?.projectKey, original.projectKey);
  assert.equal(upgraded.getSession("legacy")?.revision, 1);
  assert.ok(upgraded.getSession("legacy")?.logicalSessionId);
  assert.ok(upgraded.getSession("legacy")?.workerIncarnationId);
  upgraded.close();
  const restarted = openDatabase(dir);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from devspace_schema_migrations where version = 19").get() as { n: number }).n, 1);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from devspace_schema_migrations where version = 20").get() as { n: number }).n, 1);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from devspace_schema_migrations where version = 21").get() as { n: number }).n, 1);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from devspace_schema_migrations where version = 22").get() as { n: number }).n, 1);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from sqlite_master where type = 'table' and name = 'orchestration_test_runs'").get() as { n: number }).n, 1);
  assert.equal((restarted.sqlite.prepare("select count(*) as n from sqlite_master where type = 'table' and name = 'orchestration_execution_evidence'").get() as { n: number }).n, 1);
  restarted.close();
});
